version: '3.9'

services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.2
    environment:
      - discovery.type=single-node

  app:
    build: .
    depends_on:
      - es

  mynginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./static:/usr/share/nginx/html
      - ./templates/index.html:/usr/share/nginx/html/index.html
    depends_on:
      - app
    

    
    

